newline_style="Unix"
use_field_init_shorthand=true
use_try_shorthand=true
group_imports="StdExternalCrate"
imports_granularity="Crate"
normalize_comments = true
reorder_impl_items = true
wrap_comments = true
comment_width = 100
