[package]
name = "prover"
version = "0.1.0"
edition = "2024"

[dependencies]
circuit.workspace = true
network.workspace = true
protocol.workspace = true
logger.workspace = true

tokio.workspace = true
eyre.workspace = true
