[package]
name = "circuit"
version = "0.1.0"
edition = "2024"

[dependencies]
ff.workspace = true

circuit_macro = { path = "macro" }
derive_more = { version = "2.0.1", features = ["display"] }
itertools.workspace = true
indexmap.workspace = true
